name: tetra_stats
description: Track your and other player stats in TETR.IO
publish_to: 'none'

version: 0.2.0+4

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  http:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vector_math: any
  sqflite: ^2.2.8+2
  sqflite_common_ffi: any
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.2
  fl_chart: ^0.62.0
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.1
  intl: ^0.18.0
  syncfusion_flutter_gauges: ^22.1.34
  file_selector: ^0.9.4
  file_picker: ^5.3.2
  slang: ^3.20.0
  slang_flutter: ^3.20.0
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/icons/app.png"
  min_sdk_android: 19 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "res/icons/app.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "res/icons/app.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "res/icons/app.png"

targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_directory: res/i18n
          output_directory: lib/i18n


flutter:
  uses-material-design: true
  assets:
     - res/avatars/tetrio_anon.png
     - res/avatars/tetrio_banned.png
     - res/icons/kagari.png
     - res/tetrio_tl_alpha_ranks/x.png
     - res/tetrio_tl_alpha_ranks/u.png
     - res/tetrio_tl_alpha_ranks/ss.png
     - res/tetrio_tl_alpha_ranks/s+.png
     - res/tetrio_tl_alpha_ranks/s.png
     - res/tetrio_tl_alpha_ranks/s-.png
     - res/tetrio_tl_alpha_ranks/a+.png
     - res/tetrio_tl_alpha_ranks/a.png
     - res/tetrio_tl_alpha_ranks/a-.png
     - res/tetrio_tl_alpha_ranks/b+.png
     - res/tetrio_tl_alpha_ranks/b.png
     - res/tetrio_tl_alpha_ranks/b-.png
     - res/tetrio_tl_alpha_ranks/c+.png
     - res/tetrio_tl_alpha_ranks/c.png
     - res/tetrio_tl_alpha_ranks/c-.png
     - res/tetrio_tl_alpha_ranks/d+.png
     - res/tetrio_tl_alpha_ranks/d.png
     - res/tetrio_tl_alpha_ranks/z.png

     - res/tetrio_badges/5mblast_1.png
     - res/tetrio_badges/5mblast_10.png
     - res/tetrio_badges/5mblast_100.png
     - res/tetrio_badges/5mblast_1000.png
     - res/tetrio_badges/20tsd.png
     - res/tetrio_badges/100player.png
     - res/tetrio_badges/allclear.png
     - res/tetrio_badges/bugbounty.png
     - res/tetrio_badges/cometopen_1.png
     - res/tetrio_badges/cometopen_2.png
     - res/tetrio_badges/cometopen_3.png
     - res/tetrio_badges/early-supporter.png
     - res/tetrio_badges/founder.png
     - res/tetrio_badges/galactic2x2_1.png
     - res/tetrio_badges/galactic2x2_2.png
     - res/tetrio_badges/galactic2x2_3.png
     - res/tetrio_badges/ggc_1.png
     - res/tetrio_badges/ggc_2.png
     - res/tetrio_badges/ggc_3.png
     - res/tetrio_badges/hdoxii_1.png
     - res/tetrio_badges/hdoxii_2.png
     - res/tetrio_badges/hdoxii_3.png
     - res/tetrio_badges/heart.png
     - res/tetrio_badges/hnprism_1.png
     - res/tetrio_badges/hnprism_2.png
     - res/tetrio_badges/hnprism_3.png
     - res/tetrio_badges/ift_1.png
     - res/tetrio_badges/ift_2.png
     - res/tetrio_badges/ift_3.png
     - res/tetrio_badges/infdev.png
     - res/tetrio_badges/kod_by_founder.png
     - res/tetrio_badges/kod_founder.png
     - res/tetrio_badges/leaderboard1.png
     - res/tetrio_badges/mmc_tabi_1.png
     - res/tetrio_badges/mmc_tabi_2.png
     - res/tetrio_badges/mmc_tabi_3.png
     - res/tetrio_badges/mmc_tabi_superlobby.png
     - res/tetrio_badges/mmc_tabi_superlobby2.png
     - res/tetrio_badges/mmc_tabi_superlobby3.png
     - res/tetrio_badges/redgevo_1.png
     - res/tetrio_badges/redgevo_2.png
     - res/tetrio_badges/redgevo_3.png
     - res/tetrio_badges/rengervl_1.png
     - res/tetrio_badges/rengervl_2.png
     - res/tetrio_badges/rengervl_3.png
     - res/tetrio_badges/sakurablend_1.png
     - res/tetrio_badges/sakurablend_2.png
     - res/tetrio_badges/sakurablend_3.png
     - res/tetrio_badges/scuncapped_1.png
     - res/tetrio_badges/scuncapped_2.png
     - res/tetrio_badges/scuncapped_3.png
     - res/tetrio_badges/secretgrade.png
     - res/tetrio_badges/sfu_raccoon_1.png
     - res/tetrio_badges/sfu_raccoon_2.png
     - res/tetrio_badges/sfu_raccoon_3.png
     - res/tetrio_badges/superlobby.png
     - res/tetrio_badges/superlobby2.png
     - res/tetrio_badges/taws_u50_1.png
     - res/tetrio_badges/taws_u50_2.png
     - res/tetrio_badges/taws_u50_3.png
     - res/tetrio_badges/tawshdsl_capped.png
     - res/tetrio_badges/tawshdsl_uncapped.png
     - res/tetrio_badges/tawsignite_expert.png
     - res/tetrio_badges/tawslg.png
     - res/tetrio_badges/tetralympic_masters.png
     - res/tetrio_badges/thaitour_1.png
     - res/tetrio_badges/thaitour_2.png
     - res/tetrio_badges/thaitour_3.png
     - res/tetrio_badges/ttsdtc_1.png
     - res/tetrio_badges/ttsdtc_2.png
     - res/tetrio_badges/ttsdtc_3.png
     - res/tetrio_badges/ubcea_1.png
     - res/tetrio_badges/ubcea_2.png
     - res/tetrio_badges/ubcea_3.png
     - res/tetrio_badges/underdog_1.png
     - res/tetrio_badges/underdog_2.png
     - res/tetrio_badges/underdog_3.png
     - res/tetrio_badges/underdog_predict.png
     - res/tetrio_badges/wpl_1.png
     - res/tetrio_badges/wpl_2.png
     - res/tetrio_badges/wpl_3.png
     - res/tetrio_badges/wplc_1.png
     - res/tetrio_badges/wplc_2.png
     - res/tetrio_badges/wplc_3.png
     - res/tetrio_badges/wplc_participation.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Eurostile Round
      fonts:
        - asset: res/fonts/EurostileRound-Black.ttf
        - asset: res/fonts/EurostileRound-BlackItalic.ttf
        - asset: res/fonts/EurostileRound-Bold.ttf
        - asset: res/fonts/EurostileRound-BoldItalic.ttf
        - asset: res/fonts/EurostileRound-Heavy.ttf
          weight: 900
        - asset: res/fonts/EurostileRound-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/EurostileRound-Italic.ttf
          style: italic
        - asset: res/fonts/EurostileRound-Medium.ttf
        - asset: res/fonts/EurostileRound-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/EurostileRound-Regular.ttf
    - family: Eurostile Round Condensed
      fonts:
        - asset: res/fonts/EurostileRoundCondensed-Heavy.ttf
        - asset: res/fonts/EurostileRoundCondensed-HeavyItalic.ttf
        - asset: res/fonts/EurostileRoundCondensed-Italic.ttf
        - asset: res/fonts/EurostileRoundCondensed-Regular.ttf
    - family: Eurostile Round Extended
      fonts:
        - asset: res/fonts/EurostileRoundExtended-Black.ttf
        - asset: res/fonts/EurostileRoundExtended-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/EurostileRoundExtended-Italic.ttf
          style: italic
        - asset: res/fonts/EurostileRoundExtended-Medium.ttf
          weight: 500
        - asset: res/fonts/EurostileRoundExtended-Regular.ttf
