on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build-and-release-windows:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.5'
      - name: Install project dependencies
        run: flutter pub get
      - name: Build artifacts
        run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: TetraStats-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          replacesArtifacts: false
          discussionCategory: autobuilded-releases
          artifacts: "build/windows/runner/Release/TetraStats-${{github.ref_name}}-windows.zip"
          tag: Auto-${{ github.run_number }}
          body: This build was builded with GitHub Action workflow
          token: ${{ secrets.TOKEN }}
  build-and-release-android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
      - run: flutter pub get
      # - run: flutter test                      // lmao. Tests? Who needs it?
      - run: flutter build apk --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          replacesArtifacts: false
          discussionCategory: autobuilded-releases
          artifacts: "build/app/outputs/apk/flutter-apk/*"
          tag: Auto-${{ github.run_number }}
          body: This build was builded with GitHub Action workflow
          token: ${{ secrets.TOKEN }}